---
APPLY_FIXES: none
DEFAULT_WORKSPACE: /tmp/lint
FILTER_REGEX_EXCLUDE: '(node_modules|dist|build|\.venv|target|coverage|\.git)'
ENABLE_LINTERS:
  - REPOSITORY_SEMGREP
  - DOCKERFILE_HADOLINT
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (tsconfig.*\.json$|\.vscode/.*\.json$)
SEMGREP_ENABLE_VERSION_CHECK: false
REPOSITORY_SEMGREP_RULESETS:
  - p/security-audit
  - p/secrets
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
JAVASCRIPT_ESLINT_CONFIG_FILE: frontend/eslint.config.js
TYPESCRIPT_ES_CONFIG_FILE: frontend/eslint.config.js
JAVASCRIPT_PRETTIER_CONFIG_FILE: frontend/prettier.config.js
TYPESCRIPT_PRETTIER_CONFIG_FILE: frontend/prettier.config.js
JAVASCRIPT_ESLINT_FILTER_REGEX_INCLUDE: ^frontend/
TYPESCRIPT_ES_FILTER_REGEX_INCLUDE: ^frontend/
JAVASCRIPT_PRETTIER_FILTER_REGEX_INCLUDE: ^frontend/
TYPESCRIPT_PRETTIER_FILTER_REGEX_INCLUDE: ^frontend/
JAVASCRIPT_ESLINT_FILTER_REGEX_EXCLUDE: (\.test\.[jt]sx?$)
JAVA_PMD_FILTER_REGEX_EXCLUDE: (test|Test)
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
